const produtos = [
  // BANDAS
  { categoria: "bandas", nome: "accept", imagem: "placas/bandas/accept.png", preco: "preço aqui" },
  { categoria: "bandas", nome: "acdc1", imagem: "placas/bandas/acdc1.png", preco: "preço aqui" },
  { categoria: "bandas", nome: "angra", imagem: "placas/bandas/Angra.png", preco: "preço aqui" },
  { categoria: "bandas", nome: "arp", imagem: "placas/bandas/arp.png", preco: "preço aqui" },
  { categoria: "bandas", nome: "bls", imagem: "placas/bandas/bls.png", preco: "preço aqui" },
  { categoria: "bandas", nome: "bs-caravan", imagem: "placas/bandas/bs-caravan.png", preco: "preço aqui" },
  { categoria: "bandas", nome: "bs-hell", imagem: "placas/bandas/bs-hell.png", preco: "preço aqui" },
  { categoria: "bandas", nome: "bs-master", imagem: "placas/bandas/bs-master.png", preco: "preço aqui" },
  { categoria: "bandas", nome: "cannibal", imagem: "placas/bandas/cannibal.png", preco: "preço aqui" },
  { categoria: "bandas", nome: "cannibal1", imagem: "placas/bandas/cannibal1.png", preco: "preço aqui" },

  // BEBIDAS
  { categoria: "bebidas", nome: "bebida1", imagem: "placas/bebidas/bebida1.png", preco: "preço aqui" },
  { categoria: "bebidas", nome: "bebida2", imagem: "placas/bebidas/bebida2.png", preco: "preço aqui" },
  { categoria: "bebidas", nome: "bebida3", imagem: "placas/bebidas/bebida3.png", preco: "preço aqui" },
  { categoria: "bebidas", nome: "bebida4", imagem: "placas/bebidas/bebida4.png", preco: "preço aqui" },
  { categoria: "bebidas", nome: "bebida5", imagem: "placas/bebidas/bebida5.png", preco: "preço aqui" },

  // FOTOS REAIS
  { categoria: "fotos-reais", nome: "foto1", imagem: "placas/fotos-reais/foto1.png", preco: "preço aqui" },
  { categoria: "fotos-reais", nome: "foto2", imagem: "placas/fotos-reais/foto2.png", preco: "preço aqui" },
  { categoria: "fotos-reais", nome: "foto3", imagem: "placas/fotos-reais/foto3.png", preco: "preço aqui" },
  { categoria: "fotos-reais", nome: "foto4", imagem: "placas/fotos-reais/foto4.png", preco: "preço aqui" },

  // GAMES
  { categoria: "games", nome: "f-zero", imagem: "placas/games/f-zero.png", preco: "preço aqui" },
  { categoria: "games", nome: "final-fantasy", imagem: "placas/games/final-fantasy.png", preco: "preço aqui" },
  { categoria: "games", nome: "free-fire", imagem: "placas/games/free-fire.png", preco: "preço aqui" },
  { categoria: "games", nome: "gta-5", imagem: "placas/games/gta-5.png", preco: "preço aqui" },
  { categoria: "games", nome: "gta-sa", imagem: "placas/games/gta-sa.png", preco: "preço aqui" },
  { categoria: "games", nome: "mortal", imagem: "placas/games/mortal.png", preco: "preço aqui" },
  { categoria: "games", nome: "pac", imagem: "placas/games/pac.png", preco: "preço aqui" },
  { categoria: "games", nome: "retro", imagem: "placas/games/retro.png", preco: "preço aqui" },
  { categoria: "games", nome: "roblox", imagem: "placas/games/roblox.png", preco: "preço aqui" },
  { categoria: "games", nome: "star-fox", imagem: "placas/games/star-fox.png", preco: "preço aqui" },

  // GARAGE
  { categoria: "garage", nome: "garage1", imagem: "placas/garage/garage1.png", preco: "preço aqui" },
  { categoria: "garage", nome: "garage2", imagem: "placas/garage/garage2.png", preco: "preço aqui" },
  { categoria: "garage", nome: "garage3", imagem: "placas/garage/garage3.png", preco: "preço aqui" },
  { categoria: "garage", nome: "garage4", imagem: "placas/garage/garage4.png", preco: "preço aqui" },
  { categoria: "garage", nome: "garage5", imagem: "placas/garage/garage5.png", preco: "preço aqui" },
  { categoria: "garage", nome: "garage6", imagem: "placas/garage/garage6.png", preco: "preço aqui" },
  { categoria: "garage", nome: "garage7", imagem: "placas/garage/garage7.png", preco: "preço aqui" },
  { categoria: "garage", nome: "garage8", imagem: "placas/garage/garage8.png", preco: "preço aqui" },
  { categoria: "garage", nome: "garage9", imagem: "placas/garage/garage9.png", preco: "preço aqui" },
  { categoria: "garage", nome: "garage10", imagem: "placas/garage/garage10.png", preco: "preço aqui" },
  { categoria: "garage", nome: "garage11", imagem: "placas/garage/garage11.png", preco: "preço aqui" },
  { categoria: "garage", nome: "garage12", imagem: "placas/garage/garage12.png", preco: "preço aqui" },

  // HOME / FRASES
  { categoria: "home-frases", nome: "amigo-familia", imagem: "placas/home-frases/amigo-familia.png", preco: "preço aqui" },
  { categoria: "home-frases", nome: "amizade", imagem: "placas/home-frases/amizade.png", preco: "preço aqui" },
  { categoria: "home-frases", nome: "beleza", imagem: "placas/home-frases/beleza.png", preco: "preço aqui" },
  { categoria: "home-frases", nome: "frase1", imagem: "placas/home-frases/frase1.png", preco: "preço aqui" },
  { categoria: "home-frases", nome: "frase2", imagem: "placas/home-frases/frase2.png", preco: "preço aqui" },
  { categoria: "home-frases", nome: "frase3", imagem: "placas/home-frases/frase3.png", preco: "preço aqui" },
  { categoria: "home-frases", nome: "frase4", imagem: "placas/home-frases/frase4.png", preco: "preço aqui" },
  { categoria: "home-frases", nome: "frase5", imagem: "placas/home-frases/frase5.png", preco: "preço aqui" },
  { categoria: "home-frases", nome: "frase6", imagem: "placas/home-frases/frase6.png", preco: "preço aqui" },

  // INFANTIL
  { categoria: "infantil", nome: "bat", imagem: "placas/infantil/bat.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "brincar", imagem: "placas/infantil/brincar.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "cachorro", imagem: "placas/infantil/cachorro.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "doces-sonhos", imagem: "placas/infantil/doces-sonhos.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "dormir", imagem: "placas/infantil/dormir.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "elefante", imagem: "placas/infantil/elefante.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "giraffa", imagem: "placas/infantil/giraffa.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "hippo", imagem: "placas/infantil/hippo.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "leao", imagem: "placas/infantil/leao.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "macaco", imagem: "placas/infantil/macaco.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "princesa", imagem: "placas/infantil/princesa.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "principe", imagem: "placas/infantil/principe.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "quartinho-abençoado-m", imagem: "placas/infantil/quartinho-abençoado-m.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "quartinho-abençoado", imagem: "placas/infantil/quartinho-abençoado.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "sonhe-alto", imagem: "placas/infantil/sonhe-alto.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "sonhe", imagem: "placas/infantil/sonhe.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "superm", imagem: "placas/infantil/superm.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "tigre", imagem: "placas/infantil/tigre.png", preco: "preço aqui" },
  { categoria: "infantil", nome: "zebra", imagem: "placas/infantil/zebra.png", preco: "preço aqui" },

  // MOTOS
  { categoria: "motos", nome: "alma-livre", imagem: "placas/motos/alma-livre.png", preco: "preço aqui" },
  { categoria: "motos", nome: "born", imagem: "placas/motos/born.png", preco: "preço aqui" },
  { categoria: "motos", nome: "deserto", imagem: "placas/motos/deserto.png", preco: "preço aqui" },
  { categoria: "motos", nome: "ferrugem", imagem: "placas/motos/ferrugem.png", preco: "preço aqui" },
  { categoria: "motos", nome: "iron-wings", imagem: "placas/motos/iron-wings.png", preco: "preço aqui" },
  { categoria: "motos", nome: "liberdade", imagem: "placas/motos/liberdade.png", preco: "preço aqui" },
  { categoria: "motos", nome: "ride-die", imagem: "placas/motos/ride-die.png", preco: "preço aqui" },
  { categoria: "motos", nome: "rock-ride1", imagem: "placas/motos/rock-ride1.png", preco: "preço aqui" },
  { categoria: "motos", nome: "rock-ride2", imagem: "placas/motos/rock-ride2.png", preco: "preço aqui" },
  { categoria: "motos", nome: "velho", imagem: "placas/motos/velho.png", preco: "preço aqui" },

  // MUSICA
  { categoria: "musica", nome: "musica1", imagem: "placas/musica/musica1.png", preco: "preço aqui" },
  { categoria: "musica", nome: "musica2", imagem: "placas/musica/musica2.png", preco: "preço aqui" },
  { categoria: "musica", nome: "musica3", imagem: "placas/musica/musica3.png", preco: "preço aqui" },
  { categoria: "musica", nome: "musica4", imagem: "placas/musica/musica4.png", preco: "preço aqui" },
  { categoria: "musica", nome: "musica5", imagem: "placas/musica/musica5.png", preco: "preço aqui" },
  { categoria: "musica", nome: "musica6", imagem: "placas/musica/musica6.png", preco: "preço aqui" },
  { categoria: "musica", nome: "musica7", imagem: "placas/musica/musica7.png", preco: "preço aqui" },
  { categoria: "musica", nome: "musica8", imagem: "placas/musica/musica8.png", preco: "preço aqui" },
  { categoria: "musica", nome: "musica9", imagem: "placas/musica/musica9.png", preco: "preço aqui" },
  { categoria: "musica", nome: "musica10", imagem: "placas/musica/musica10.png", preco: "preço aqui" },
  { categoria: "musica", nome: "musica11", imagem: "placas/musica/musica11.png", preco: "preço aqui" },
  { categoria: "musica", nome: "musica12", imagem: "placas/musica/musica12.png", preco: "preço aqui" },

  // RPG
  { categoria: "rpg", nome: "3magos", imagem: "placas/rpg/3magos.png", preco: "preço aqui" },
  { categoria: "rpg", nome: "abobora", imagem: "placas/rpg/abobora.png", preco: "preço aqui" },
  { categoria: "rpg", nome: "adaga", imagem: "placas/rpg/adaga.png", preco: "preço aqui" },
  { categoria: "rpg", nome: "arco", imagem: "placas/rpg/arco.png", preco: "preço aqui" },
  { categoria: "rpg", nome: "espada-gelo", imagem: "placas/rpg/espada-gelo.png", preco: "preço aqui" },
  { categoria: "rpg", nome: "gelo", imagem: "placas/rpg/gelo.png", preco: "preço aqui" },
  { categoria: "rpg", nome: "machado", imagem: "placas/rpg/machado.png", preco: "preço aqui" },
  { categoria: "rpg", nome: "mapa", imagem: "placas/rpg/mapa.png", preco: "preço aqui" },
  { categoria: "rpg", nome: "nature", imagem: "placas/rpg/nature.png", preco: "preço aqui" },
  { categoria: "rpg", nome: "pureza", imagem: "placas/rpg/pureza.png", preco: "preço aqui" },

  // STREET
  { categoria: "street", nome: "chao", imagem: "placas/street/chao.png", preco: "preço aqui" },
  { categoria: "street", nome: "hh-h", imagem: "placas/street/hh-h.png", preco: "preço aqui" },
  { categoria: "street", nome: "hh-m", imagem: "placas/street/hh-m.png", preco: "preço aqui" },
  { categoria: "street", nome: "jacketa", imagem: "placas/street/jacketa.png", preco: "preço aqui" },
  { categoria: "street", nome: "naipess", imagem: "placas/street/naipess.png", preco: "preço aqui" },
  { categoria: "street", nome: "naopedelicença", imagem: "placas/street/naopedelicença.png", preco: "preço aqui" },
  { categoria: "street", nome: "paz-spray", imagem: "placas/street/paz-spray.png", preco: "preço aqui" },
  { categoria: "street", nome: "role-sem-fim", imagem: "placas/street/role-sem-fim.png", preco: "preço aqui" },
  { categoria: "street", nome: "skate1", imagem: "placas/street/skate1.png", preco: "preço aqui" },
  { categoria: "street", nome: "skate2", imagem: "placas/street/skate2.png", preco: "preço aqui" },
  { categoria: "street", nome: "skate3", imagem: "placas/street/skate3.png", preco: "preço aqui" },
  { categoria: "street", nome: "skateh", imagem: "placas/street/skateh.png", preco: "preço aqui" },
  { categoria: "street", nome: "skatem", imagem: "placas/street/skatem.png", preco: "preço aqui" },
  { categoria: "street", nome: "skatista", imagem: "placas/street/skatista.png", preco: "preço aqui" },
  { categoria: "street", nome: "som", imagem: "placas/street/som.png", preco: "preço aqui" },
  { categoria: "street", nome: "voz", imagem: "placas/street/voz.png", preco: "preço aqui" },
  { categoria: "street", nome: "zap-mineiro", imagem: "placas/street/zap-mineiro.png", preco: "preço aqui" },

  // TRIP
  { categoria: "trip", nome: "crazy", imagem: "placas/trip/crazy.png", preco: "preço aqui" },
  { categoria: "trip", nome: "derretendo", imagem: "placas/trip/derretendo.png", preco: "preço aqui" },
  { categoria: "trip", nome: "economico", imagem: "placas/trip/economico.png", preco: "preço aqui" },
  { categoria: "trip", nome: "meditando", imagem: "placas/trip/meditando.png", preco: "preço aqui" }
];
